/*
 * This source file was generated by the Gradle 'init' task
 */
package org.localcloud;

import org.localcloud.Data.AppProperties;
import org.localcloud.Data.DBProperties;
import org.localcloud.db.DB;
import org.localcloud.db.UserDB;
import org.localcloud.server.MainServer;

import java.sql.SQLException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        AppProperties.loadProperties();
        DB.loadDBInstance();
        DBProperties.loadProperties();

        MainServer.startServer();
    }
}
