db.user.id=postgres
db.port.no=9191
db.password=javidh17
db.url=jdbc:postgresql://localhost:9191/localcloud_db

db.schema.user.userid=userid
db.schema.user.password=password
db.schema.user.role=role
db.schema.user.pk=id

server.cookie.session.expire=3600